/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jiren
 */
public class PassedLogin extends javax.swing.JFrame {

    /**
     * Creates new form PassedLogin
     */
    public PassedLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Add_Patient = new javax.swing.JButton();
        Patients = new javax.swing.JButton();
        Medicine = new javax.swing.JButton();
        Worker = new javax.swing.JButton();
        Add_Worker = new javax.swing.JButton();
        Add_Medicine = new javax.swing.JButton();
        System_Admin = new javax.swing.JButton();
        Remove_Medicine = new javax.swing.JButton();
        Remove_Patient = new javax.swing.JButton();
        Edit_System = new javax.swing.JButton();
        Remove_Worker1 = new javax.swing.JButton();
        Add_Admin = new javax.swing.JButton();
        Remove_Admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Add_Patient.setText("Add Patient");
        Add_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_PatientActionPerformed(evt);
            }
        });

        Patients.setText("Patients");
        Patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsActionPerformed(evt);
            }
        });

        Medicine.setText("Medicine");
        Medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineActionPerformed(evt);
            }
        });

        Worker.setText("Worker");
        Worker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerActionPerformed(evt);
            }
        });

        Add_Worker.setText("Add Worker");
        Add_Worker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_WorkerActionPerformed(evt);
            }
        });

        Add_Medicine.setText("Add Medicine");
        Add_Medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_MedicineActionPerformed(evt);
            }
        });

        System_Admin.setText("System Admin");
        System_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System_AdminActionPerformed(evt);
            }
        });

        Remove_Medicine.setText("Remove Medicine");
        Remove_Medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_MedicineActionPerformed(evt);
            }
        });

        Remove_Patient.setText("Remove Patient");
        Remove_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_PatientActionPerformed(evt);
            }
        });

        Edit_System.setText("Edit System");
        Edit_System.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_SystemActionPerformed(evt);
            }
        });

        Remove_Worker1.setText("Remove Worker");
        Remove_Worker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_Worker1ActionPerformed(evt);
            }
        });

        Add_Admin.setText("Add Admin");
        Add_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_AdminActionPerformed(evt);
            }
        });

        Remove_Admin.setText("Remove Admin");
        Remove_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Remove_Patient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Patients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Patient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Medicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add_Medicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Remove_Medicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Remove_Worker1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Worker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Add_Worker, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Add_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(System_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Remove_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(Edit_System, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Patients)
                    .addComponent(Worker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Patient)
                    .addComponent(Add_Worker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Remove_Patient)
                    .addComponent(Remove_Worker1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Medicine)
                    .addComponent(System_Admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Medicine)
                    .addComponent(Add_Admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Remove_Medicine)
                    .addComponent(Remove_Admin))
                .addGap(18, 18, 18)
                .addComponent(Edit_System)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_PatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_PatientActionPerformed

    private void Add_WorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_WorkerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_WorkerActionPerformed

    private void PatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsActionPerformed

    private void Add_MedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_MedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_MedicineActionPerformed

    private void MedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineActionPerformed

    private void Remove_MedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_MedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remove_MedicineActionPerformed

    private void System_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_System_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_System_AdminActionPerformed

    private void Remove_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_PatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remove_PatientActionPerformed

    private void WorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkerActionPerformed

    private void Edit_SystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_SystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_SystemActionPerformed

    private void Remove_Worker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_Worker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remove_Worker1ActionPerformed

    private void Add_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_AdminActionPerformed

    private void Remove_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remove_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassedLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassedLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassedLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassedLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassedLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Admin;
    private javax.swing.JButton Add_Medicine;
    private javax.swing.JButton Add_Patient;
    private javax.swing.JButton Add_Worker;
    private javax.swing.JButton Edit_System;
    private javax.swing.JButton Medicine;
    private javax.swing.JButton Patients;
    private javax.swing.JButton Remove_Admin;
    private javax.swing.JButton Remove_Medicine;
    private javax.swing.JButton Remove_Patient;
    private javax.swing.JButton Remove_Worker1;
    private javax.swing.JButton System_Admin;
    private javax.swing.JButton Worker;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
